### ISSUE TITLE
Request : Firefox webextension

### ISSUE THREAD

**Issue by florentulve** [jleroy/Cocktail#4]
Bonjour,

Un portage de l'extension est-il envisagé ?

**Comment by jleroy** [comment]
J'ai fait quelques modifs pour tester et l'extension semble fonctionner sous Firefox 57. 
Il y a juste quelques bugs d'affichage mineurs. 

Je regarde pour faire ça de façon propre et publier une version Firefox dès que j'ai un peu de temps.

**Comment by Gildas-GH** [comment]
Bonsoir,
Des nouvelles pour la WebExtension?

j'ai essayé d'installer l'extension Chrome avec [Chrome Store Foxified](https://addons.mozilla.org/fr/firefox/addon/chrome-store-foxified/) conseillé [ici](http://www.macg.co/logiciels/2017/01/molochrome-une-extension-pour-utiliser-molotov-dans-chrome-et-firefox-96960) mais Molotov indique une erreur lors de la connexion (en login/mot de passe) :
> Nous avons rencontré une erreur, nous nous excusons pour la gêne occasionnée

J'ai éssayé l'extension sur Chromium, ou il n'y a aucun problème... Y a-t-il un autre moyen de l'installer? ("l'extension semble fonctionner")

Merci beaucoup!

**Comment by jleroy** [comment]
@florentulve @Gildas-GH Voici une version de test de l'extension pour Firefox : [cocktail-1.2.0-an+fx.xpi.zip](https://github.com/jleroy/Cocktail/files/1485174/cocktail-1.2.0-an.fx.xpi.zip)

Il vous suffit de dézipper le fichier, puis de l'installer dans Firefox via le menu "Modules complémentaires" (about:addons) > Roue dentée > "Installer un module depuis un fichier".

Tout semble fonctionner, seule l'icône de de l'extension ne s'affiche par dans la barre d'outil (c'est l'icône "puzzle" par défaut qui s'affiche). Si vous pouviez tester et me signaler les éventuels bugs. :)

**Comment by florentulve** [comment]
Pas de pb de mon côté. L'extension fonctionne avec Firefox nightly

**Comment by Gildas-GH** [comment]
Bonjour,
Merci beaucoup pour le fichier, tout marche très bien dans Firefox 57 pour moi, je reviendrais vous voir si je rencontre un soucis!

Bonne soirée!

**Comment by jleroy** [comment]
Le module pour Firefox est désormais disponible de façon officielle [ici](https://addons.mozilla.org/fr/firefox/addon/cocktail-molotov/).

Je vous conseille de supprimer le module que je vous ai envoyé précédemment puis de le réinstaller depuis ce lien afin de profiter automatiquement des mises à jour futures.
