### ISSUE TITLE
Extension cocktail sur Chromium sur Rapsberry pi 3

### ISSUE THREAD

**Issue by sarahetmathis** [jleroy/Cocktail#6]
Bonjour,

J'ai réussi à installer cocktail et lancer Molotov et à me connecter.
Par contre lorsque je lance le direct ça reste bloqué et pas de lecture.
Peut n'est pas encore optimisé pour le raspberry ?

Cordialement

Luc

**Comment by jleroy** [comment]
Bonjour, 

Chromium ne contient pas les codecs nécessaires (et propriétaires) au fonctionnement de l'application Molotov. Il est donc nécessaire d'utiliser la version "commerciale" de Chromium : Google Chrome.

Voir [cette vidéo](https://www.youtube.com/watch?v=nidFG0Zta4w) pour plus de détails sur les différences entre Chromium et Google Chrome.

**Comment by sarahetmathis** [comment]
Bonjour,

Merci pour votre réponse. Cela m'a bien éclairé.
Tout nouveau dans le monde raspberry, je vois bien qu'il faut trouver des alternatives aux programmes des PC de Mr tout le monde.
Donc me reste plus qu'à trouver Google Chrome pour le raspberry s'il existe. ;)

Merci

Envoyé de mon iPhone
