### ISSUE TITLE
Problèmes d'affichage récent

### ISSUE THREAD

**Issue by Bundy01** [jleroy/Cocktail#8]
Bonjour,
comme dis dans le titre, je n'ai plus accès aux infos des chaînes...
L'application molotov à été mise à jour récement, peut être un soucis avec le user-agent ?

capture d'écran: https://framapic.org/8EnTeOEsgux2/ffUVQIweAGD8.png

**Comment by jleroy** [comment]
Merci pour la remontée, je regarde.

**Comment by jleroy** [comment]
Le souci à l'air d'être côté Molotov... J'essaie de voir ça avec eux.

**Comment by aiitidh** [comment]
Bonjour même bug que sur le Screenshots et de plus la fenêtre de visionnage ce réduit , une bande grise apparais sur le coté gauche qui apparemment s'agrandit de jour en jour

**Comment by jleroy** [comment]
Le problème semble avoir été résolu chez Molotov : vous confirmez ?

**Comment by aiitidh** [comment]
Oui tout est refonctionne correctement, merci

Le ven. 29 juin 2018 à 23:04, Jonathan Leroy <notifications@github.com> a
écrit :

**Comment by Bundy01** [comment]
Je confirme, problème résolu.
