### ISSUE TITLE
Problèmes avec waterfox

### ISSUE THREAD

**Issue by Bundy01** [jleroy/Cocktail#9]
Bonjour,
j'ai installé Waterfox récemment avec Cocktail bien entendu ;) 
Le problème est que je n'ai plus accès aux chaînes (j'ai un rond coloré, comme dans les temps anciens ou les programmes se coupaient dans la nuit).
Le problème vient-il du serveur de molotov ou c'est l'application qui ne supporte pas Waterfox ?

**Comment by jleroy** [comment]
Bonjour, 

L'affichage de la mire signifie très probablement que le navigateur utilisé ne supporte pas les DRM nécessaires à la lecture des flux Molotov.

Je ne connais pas Waterfox, mais il semble avoir une option pour activer le support des DRM dans le menu Préférences > Contenu. As-tu essayé de l'activer ?

**Comment by Bundy01** [comment]
Widevine est bien activé, par contre j'ai une chaîne qui fonctionne: c'est INA.
Les autres soit la mire apparaît soit c'est un écran noir :/
Il n'y a pas de problèmes chez toi ?

**Comment by Bundy01** [comment]
Je pencherais pour un problème chez molotov. Je viens d'installer le logiciel et c'est pareil, je n'ai accès qu'a INA. Peux-tu me confirmer ?

**Comment by jleroy** [comment]
Est-ce que tu te connectes depuis l'étranger ou via un VPN ? Si oui, il est normal que tu n'ai pas accès aux flux. 
Si tu es bien en France et que le problème persiste avec l'appli officielle, alors le souci vient de chez Molotov.

**Comment by Bundy01** [comment]
J'utilise bien un VPN. Ça marchait très bien avant :/ J'ai même essayé avec une ip en France mais le résultat est identique.

**Comment by jleroy** [comment]
Une IP d'un FAI français ou une IP française sur un VPN ? Dans le second cas, ça ne fonctionnera pas.
Je suppose qu'ils ont durcis leurs filtrages à la demande des diffuseurs.

**Comment by Bundy01** [comment]
IP française sur un VPN, dommage même si je ne suis pas un fan de TV ça pouvait dépanner. Je clos cette issue.  
Merci pour ton aide.
